---
- hosts: Splunk
  vars:
    - lifecycle: install
  roles:
    - preparation_splunk
    - splunk_base

- hosts: Manager
  vars:
    - lifecycle: install
  roles:
    - manager

- hosts: DeploymentServer
  vars:
    - lifecycle: install
  roles:
    - preparation_splunk
    - splunk_base

- hosts: Deployer
  vars:
    - lifecycle: install
  roles:
    - deployer

- hosts: peer1,peer2
  vars:
    - lifecycle: install
    - site: site1
  roles:
    - peer

- hosts: peer3,peer4
  vars:
    - lifecycle: install
    - site: site2
  roles:
    - peer

- hosts: searchhead1
  vars:
    - lifecycle: install
    - site: site1
    - self_ip: 172.31.8.45
  roles:
    - searchhead

- hosts: searchhead2
  vars:
    - lifecycle: install
    - site: site1
    - self_ip: 172.31.1.134
  roles:
    - searchhead

- hosts: searchhead3
  vars:
    - lifecycle: install
    - site: site1
    - self_ip: 172.31.13.54
  roles:
    - searchhead

- hosts: searchhead1
  vars:
    - lifecycle: install
    - self_ip: 172.31.8.45
  roles:
    - shc_captain

- hosts: UniversalForwarder
  vars:
    - lifecycle: install
    - src_file: splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz
  roles:
    - preparation_splunk
    - universalforwarder