---
- name: Create new manager-app
  become: yes
  file:
    path: /opt/splunk/etc/manager-apps/floble
    owner: splunk
    group: splunk
    state: directory
  when: lifecycle == "manager"

- name: Create new manager-app sub-directory
  become: yes
  file:
    path: /opt/splunk/etc/manager-apps/floble/local
    owner: splunk
    group: splunk
    state: directory
  when: lifecycle == "manager"

- name: Copy the indexes.conf to the system directory
  become: yes
  template:
    src: indexes.conf.j2
    dest: /opt/splunk/etc/manager-apps/floble/local/indexes.conf
    owner: splunk
    group: splunk
  when: lifecycle == "manager"

#- name: Copy the props.conf to the system directory
#  become: yes
#  template:
#    src: props.conf.j2
#    dest: /opt/splunk/etc/manager-apps/floble/local/props.conf
#    owner: splunk
#    group: splunk
#    mode: 0744
#  when: lifecycle == "manager"

#- name: Copy the transforms.conf to the system directory
#  become: yes
#  template:
#    src: transforms.conf.j2
#    dest: /opt/splunk/etc/manager-apps/floble/local/transforms.conf
#    owner: splunk
#    group: splunk
#    mode: 0744
#  when: lifecycle == "manager"

#- name: Make the splunk user the owner of the splunk installation directory
#  become: yes
#  file:
#    path: /opt/splunk
#    owner: splunk
#    group: splunk
#    mode: 0744
#    recurse: yes
#  when: lifecycle == "manager"

- name: Login as admin
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk search 'index=_internal | fields _time | head 1 ' -auth '{{ admin_user_name }}:{{ admin_password }}'"
  when: lifecycle == "manager"

- name: Validate the new cluster bundle
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk validate cluster-bundle --check-restart"
  when: lifecycle == "manager"

- name: Deploy the cluster bundle
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk apply cluster-bundle"
  when: lifecycle == "manager"

- name: Create new deployment-app
  become: yes
  file:
    path: /opt/splunk/etc/deployment-apps/yuma
    owner: splunk
    group: splunk
    state: directory
  when: lifecycle == "deploymentserver"

- name: Create new deployment-app sub-directory
  become: yes
  file:
    path: /opt/splunk/etc/deployment-apps/yuma/local
    owner: splunk
    group: splunk
    state: directory
  when: lifecycle == "deploymentserver"

- name: Copy the inputs.conf to the app directory
  become: yes
  template:
    src: inputs.conf.j2
    dest: /opt/splunk/etc/deployment-apps/yuma/local/inputs.conf
    owner: splunk
    group: splunk
  when: lifecycle == "deploymentserver"

#- name: Make the splunk user the owner of the splunk installation directory
#  become: yes
#  file:
#    path: /opt/splunk
#    owner: splunk
#    group: splunk
#    mode: 0744
#    recurse: yes
#  when: lifecycle == "deploymentserver"

- name: Login as admin
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk search 'index=_internal | fields _time | head 1 ' -auth '{{ admin_user_name }}:{{ admin_password }}'"
  when: lifecycle == "deploymentserver"

- name: Reload the deployment server
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk reload deploy-server"
  when: lifecycle == "deploymentserver"