---
- name: Create new shcluster-app
  become: yes
  file:
    path: /opt/splunk/etc/shcluster/apps/isa
    owner: splunk
    group: splunk
    state: directory
  when: lifecycle == "deployer"

- name: Create new shcluster-app sub-directory
  become: yes
  file:
    path: /opt/splunk/etc/shcluster/apps/isa/default
    owner: splunk
    group: splunk
    state: directory
  when: lifecycle == "deployer"

- name: Copy the app.conf to the shcluster-app directory
  become: yes
  template:
    src: app.conf.j2
    dest: /opt/splunk/etc/shcluster/apps/isa/default/app.conf
    owner: splunk
    group: splunk
  when: lifecycle == "deployer"

- name: Stage the shcluster-bundle
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk apply shcluster-bundle -action stage --answer-yes -force 1"
  when: lifecycle == "deployer"

- name: Push the shcluster-bundle
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk apply shcluster-bundle -action send -target https://{{ sh1_ip }}:{{ splunkd_port }} --answer-yes -force 1"
  when: lifecycle == "deployer"

- name: Restart the shcluster
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk rolling-restart shcluster-members"
  when: lifecycle == "deployer"