---
- name: Unarchive the installation files to the default splunk directory
  become: yes
  unarchive:
    src: "/tmp/splunk/{{ src_file }}"
    remote_src: yes
    dest: /opt
    owner: splunk
    group: splunk
    mode: 0744
  when: lifecycle == "install"

- name: Copy password file to remote host
  become: yes
  template:
    src: user-seed.conf.j2
    dest: /opt/splunk/etc/system/local/user-seed.conf
    owner: splunk
    group: splunk
    mode: 0744
  when: lifecycle == "install"

- name: Make the splunk user the owner of the splunk installation directory
  become: yes
  file:
    path: /opt/splunk
    owner: splunk
    group: splunk
    mode: 0744
    recurse: yes
  when: lifecycle == "install"

- name: Start the splunk service
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk start --accept-license"
  when: lifecycle == "install"

- name: Stop the splunk service
  become: yes
  become_user: splunk
  shell: "/opt/splunk/bin/splunk stop"
  when: lifecycle == "remove"

- name: Remove the default splunk directory
  become: yes
  become_user: splunk
  file:
    path: /opt/splunk/
    state: absent
  when: lifecycle == "remove"